spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: serviceA
        uri: lb://service-A
        predicates:
        - Path=/servicea/**
        filters:
        - RewritePath=/servicea/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-srvA
            fallbackUri: forward:/fallback/serviceA
      - id: ServiceB
        uri: lb://service-B
        predicates:
        - Path=/serviceb/**
        filters:
        - RewritePath=/serviceb/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-srvB
            fallbackUri: forward:/fallback/serviceB  
    consul:
      discovery:
        instanceId: Gateway
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
hystrix:
   dashboard:
       proxy-stream-allow-list: "*"
